// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/student.proto

package gosample_srv_student

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f512b57901e127c8, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Student struct {
	StuId                int32    `protobuf:"varint,1,opt,name=stuId,proto3" json:"stuId,omitempty"`
	StuName              string   `protobuf:"bytes,2,opt,name=stuName,proto3" json:"stuName,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_f512b57901e127c8, []int{1}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetStuId() int32 {
	if m != nil {
		return m.StuId
	}
	return 0
}

func (m *Student) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *Student) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Student) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

type StudentResponse struct {
	StuId                int32    `protobuf:"varint,1,opt,name=stuId,proto3" json:"stuId,omitempty"`
	StuName              string   `protobuf:"bytes,2,opt,name=stuName,proto3" json:"stuName,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentResponse) Reset()         { *m = StudentResponse{} }
func (m *StudentResponse) String() string { return proto.CompactTextString(m) }
func (*StudentResponse) ProtoMessage()    {}
func (*StudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f512b57901e127c8, []int{2}
}

func (m *StudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentResponse.Unmarshal(m, b)
}
func (m *StudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentResponse.Marshal(b, m, deterministic)
}
func (m *StudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentResponse.Merge(m, src)
}
func (m *StudentResponse) XXX_Size() int {
	return xxx_messageInfo_StudentResponse.Size(m)
}
func (m *StudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StudentResponse proto.InternalMessageInfo

func (m *StudentResponse) GetStuId() int32 {
	if m != nil {
		return m.StuId
	}
	return 0
}

func (m *StudentResponse) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *StudentResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *StudentResponse) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

// 返回学生id
type ResponseStudentId struct {
	StuId                int32    `protobuf:"varint,1,opt,name=stuId,proto3" json:"stuId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStudentId) Reset()         { *m = ResponseStudentId{} }
func (m *ResponseStudentId) String() string { return proto.CompactTextString(m) }
func (*ResponseStudentId) ProtoMessage()    {}
func (*ResponseStudentId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f512b57901e127c8, []int{3}
}

func (m *ResponseStudentId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStudentId.Unmarshal(m, b)
}
func (m *ResponseStudentId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStudentId.Marshal(b, m, deterministic)
}
func (m *ResponseStudentId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStudentId.Merge(m, src)
}
func (m *ResponseStudentId) XXX_Size() int {
	return xxx_messageInfo_ResponseStudentId.Size(m)
}
func (m *ResponseStudentId) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStudentId.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStudentId proto.InternalMessageInfo

func (m *ResponseStudentId) GetStuId() int32 {
	if m != nil {
		return m.StuId
	}
	return 0
}

type Response struct {
	// 响应是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 响应信息
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f512b57901e127c8, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "gosample.srv.student.Request")
	proto.RegisterType((*Student)(nil), "gosample.srv.student.Student")
	proto.RegisterType((*StudentResponse)(nil), "gosample.srv.student.StudentResponse")
	proto.RegisterType((*ResponseStudentId)(nil), "gosample.srv.student.ResponseStudentId")
	proto.RegisterType((*Response)(nil), "gosample.srv.student.Response")
}

func init() { proto.RegisterFile("proto/student.proto", fileDescriptor_f512b57901e127c8) }

var fileDescriptor_f512b57901e127c8 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0xb5, 0xa6, 0x1d, 0xf1, 0xdf, 0xda, 0xc3, 0x52, 0x50, 0xca, 0x82, 0x50, 0x2f,
	0x2b, 0x28, 0xf8, 0x05, 0x3c, 0x15, 0x44, 0x64, 0x8b, 0x47, 0x0f, 0x31, 0x19, 0x42, 0xc1, 0x34,
	0x31, 0x33, 0x5b, 0xfa, 0xd5, 0xfc, 0x76, 0xb2, 0x9b, 0x5d, 0xbd, 0x04, 0x3d, 0xf5, 0x36, 0x6f,
	0xde, 0xf0, 0x7e, 0x8f, 0x64, 0xe1, 0xa2, 0x69, 0x6b, 0xae, 0x6f, 0x89, 0x6d, 0x81, 0x6b, 0xd6,
	0x5e, 0x89, 0x49, 0x59, 0x53, 0x56, 0x35, 0x1f, 0xa8, 0xa9, 0xdd, 0xe8, 0xe0, 0xa9, 0x31, 0xa4,
	0x06, 0x3f, 0x2d, 0x12, 0xab, 0x37, 0x48, 0x97, 0xdd, 0x56, 0x4c, 0x60, 0x48, 0x6c, 0x17, 0x85,
	0x4c, 0x66, 0xc9, 0x7c, 0x68, 0x3a, 0x21, 0x24, 0xa4, 0xc4, 0xf6, 0x39, 0xab, 0x50, 0xee, 0xcf,
	0x92, 0xf9, 0xd8, 0x44, 0x29, 0xce, 0x60, 0x90, 0x95, 0x28, 0x07, 0xfe, 0xda, 0x8d, 0x6e, 0x43,
	0xb8, 0x95, 0x07, 0xdd, 0x86, 0x70, 0xab, 0x10, 0x4e, 0x43, 0xbc, 0x41, 0x6a, 0xea, 0x35, 0xe1,
	0x4e, 0x30, 0x37, 0x70, 0x1e, 0xf3, 0x03, 0x6e, 0x51, 0xf4, 0x83, 0xd4, 0x03, 0x8c, 0x7e, 0xaa,
	0x38, 0xa8, 0xcd, 0x73, 0x24, 0xf2, 0x37, 0x23, 0x13, 0xa5, 0x43, 0x54, 0x54, 0x86, 0x2a, 0x6e,
	0xbc, 0xfb, 0x4a, 0xe0, 0x24, 0x64, 0x2f, 0xb1, 0xdd, 0xac, 0x72, 0x14, 0x2f, 0x70, 0xfc, 0xd8,
	0x62, 0xc6, 0x91, 0x29, 0x2e, 0x75, 0xdf, 0xe7, 0xd6, 0xc1, 0x9e, 0x5e, 0xf5, 0xdb, 0xb1, 0x8e,
	0xda, 0x13, 0xaf, 0x70, 0xf4, 0xb4, 0x22, 0xfe, 0x27, 0x2f, 0xfc, 0xbb, 0xe9, 0xf5, 0x9f, 0xb8,
	0xdf, 0xd8, 0xf7, 0x43, 0xff, 0x18, 0xee, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xee, 0xc4, 0x68,
	0x4f, 0x23, 0x02, 0x00, 0x00,
}
