// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/student.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f512b57901e127c8, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Student struct {
	StuId                int32    `protobuf:"varint,1,opt,name=stuId,proto3" json:"stuId,omitempty"`
	StuName              string   `protobuf:"bytes,2,opt,name=stuName,proto3" json:"stuName,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_f512b57901e127c8, []int{1}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetStuId() int32 {
	if m != nil {
		return m.StuId
	}
	return 0
}

func (m *Student) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

func (m *Student) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Student) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

type ListResponse struct {
	Code                 string     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Students             []*Student `protobuf:"bytes,3,rep,name=students,proto3" json:"students,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f512b57901e127c8, []int{2}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListResponse) GetStudents() []*Student {
	if m != nil {
		return m.Students
	}
	return nil
}

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f512b57901e127c8, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "gosample.srv.student.Request")
	proto.RegisterType((*Student)(nil), "gosample.srv.student.Student")
	proto.RegisterType((*ListResponse)(nil), "gosample.srv.student.ListResponse")
	proto.RegisterType((*Response)(nil), "gosample.srv.student.Response")
}

func init() { proto.RegisterFile("proto/student.proto", fileDescriptor_f512b57901e127c8) }

var fileDescriptor_f512b57901e127c8 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x6d, 0xbe, 0xb4, 0x5f, 0x9a, 0xa9, 0x8a, 0x8c, 0x3d, 0x2c, 0x05, 0x25, 0xec, 0x29, 0xa7,
	0x55, 0xea, 0xc9, 0xb3, 0x27, 0x41, 0x44, 0xb6, 0x67, 0x0f, 0xb1, 0x19, 0x42, 0xc1, 0x74, 0x63,
	0x66, 0x53, 0xfa, 0xcb, 0xfc, 0x7d, 0xb2, 0x9b, 0x8d, 0x78, 0x08, 0x8a, 0xb7, 0x99, 0x79, 0xb3,
	0xef, 0xbd, 0x7d, 0x03, 0x17, 0x4d, 0x6b, 0xac, 0xb9, 0x66, 0xdb, 0x95, 0xb4, 0xb7, 0xca, 0x77,
	0xb8, 0xac, 0x0c, 0x17, 0x75, 0xf3, 0x46, 0x8a, 0xdb, 0x83, 0x0a, 0x98, 0x4c, 0x21, 0xd1, 0xf4,
	0xde, 0x11, 0x5b, 0xf9, 0x02, 0xc9, 0xa6, 0x9f, 0xe2, 0x12, 0x66, 0x6c, 0xbb, 0x87, 0x52, 0x44,
	0x59, 0x94, 0xcf, 0x74, 0xdf, 0xa0, 0x80, 0x84, 0x6d, 0xf7, 0x54, 0xd4, 0x24, 0xfe, 0x65, 0x51,
	0x9e, 0xea, 0xa1, 0xc5, 0x73, 0x88, 0x8b, 0x8a, 0x44, 0xec, 0xb7, 0x5d, 0xe9, 0x26, 0x4c, 0x47,
	0x31, 0xed, 0x27, 0x4c, 0x47, 0x69, 0xe0, 0xe4, 0x71, 0xc7, 0x56, 0x13, 0x37, 0x66, 0xcf, 0x84,
	0x08, 0xd3, 0xad, 0x29, 0xc9, 0x4b, 0xa4, 0xda, 0xd7, 0xee, 0x55, 0xcd, 0x55, 0x60, 0x77, 0x25,
	0xde, 0xc1, 0x3c, 0x58, 0x65, 0x11, 0x67, 0x71, 0xbe, 0x58, 0x5f, 0xaa, 0xb1, 0x8f, 0xa8, 0x60,
	0x5d, 0x7f, 0xad, 0xcb, 0x1b, 0x98, 0xff, 0x4d, 0x6c, 0xfd, 0x11, 0xc1, 0x59, 0xe0, 0xd9, 0x50,
	0x7b, 0xd8, 0x6d, 0x09, 0x9f, 0xe1, 0xf4, 0xbe, 0xa5, 0xc2, 0xd2, 0x10, 0xcd, 0xcf, 0xf2, 0xab,
	0xab, 0x71, 0x78, 0x30, 0x22, 0x27, 0xa8, 0x61, 0xe1, 0x72, 0xf8, 0x85, 0x2f, 0x1c, 0x65, 0x25,
	0xc7, 0xe1, 0xef, 0x49, 0xca, 0xc9, 0xeb, 0x7f, 0x7f, 0xe2, 0xdb, 0xcf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd2, 0xc2, 0x80, 0x19, 0xf9, 0x01, 0x00, 0x00,
}
